create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  admission_no text unique not null,
  full_name text not null,
  class_name text not null,
  guardian_name text,
  phone text,
  email text
);
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('Present', 'Absent', 'Late'))
);
create table if not exists public.fee_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  amount numeric(10,2) not null,
  payment_date date not null,
  status text not null check (status in ('Paid', 'Pending', 'Overdue')),
  note text
);
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  subject text,
  phone text,
  email text
);
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  course_name text not null,
  class_name text not null,
  teacher_name text
);
create table if not exists public.marks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  subject text not null,
  score integer not null,
  term text not null
);
create table if not exists public.library_books (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  author text,
  isbn text,
  total_copies integer not null check (total_copies >= 0),
  available_copies integer not null check (available_copies >= 0)
);
create table if not exists public.library_loans (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  book_id bigint references public.library_books(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  issue_date date not null,
  due_date date not null,
  return_date date,
  status text not null check (status in ('Issued', 'Returned', 'Overdue')),
  fine_amount numeric(10,2) not null default 0
);
create table if not exists public.student_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null default '',
  admission_no text not null default '',
  class_name text not null default '',
  guardian_name text not null default '',
  phone text not null default '',
  email text not null default '',
  username text unique not null,
  password text not null,
  role text not null default 'student',
  student_id bigint
);
-- Admin Signup
create table if not exists public.admin_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'admin',
  admin_id bigint
);
-- Move any older admin account out of the student account table.
insert into public.admin_signup (full_name, phone, email, username, password, role)
select full_name, phone, email, username, password, 'admin'
from public.student_signup
where role = 'admin'
on conflict (username) do nothing;

delete from public.student_signup where role = 'admin';

-- Teacher Signup
create table if not exists public.teacher_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  subject text,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'teacher',
  teacher_id bigint
);
-- Principal Signup
create table if not exists public.principal_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'principal',
  principal_id bigint
);
-- Accountant Signup
create table if not exists public.accountant_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'accountant',
  accountant_id bigint
);
-- Librarian Signup
create table if not exists public.librarian_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'librarian',
  librarian_id bigint
);
